# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    secret.yml                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kefujiwa <kefujiwa@student.42tokyo.jp>     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/05/15 02:34:14 by kefujiwa          #+#    #+#              #
#    Updated: 2021/05/24 01:29:20 by kefujiwa         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Secret
metadata:
  name: ft-secret
type: Opaque
data:
  mysql_pass: cGFzc3dvcmQ= # echo -n 'password' | base64
  db_name: d29yZHByZXNz # echo -n 'wordpress' | base64
  db_user: dXNlcg== # echo -n 'user' | base64
  db_pass: cGFzc3dvcmQ= # echo -n 'password' | base64
  influxdb_user: dXNlcg== # echo -n 'user' | base64
  influxdb_pass: cGFzc3dvcmQ= # echo -n 'password' | base64
