# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    mysql.yml                                          :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kefujiwa <kefujiwa@student.42tokyo.jp>     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/05/24 01:21:13 by kefujiwa          #+#    #+#              #
#    Updated: 2021/05/25 18:25:54 by kefujiwa         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: kefujiwa/mysql:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
        livenessProbe:
          exec:
            command: ["/bin/sh", "-c", "pgrep telegraf && pgrep mysqld"]
          initialDelaySeconds: 10
          periodSeconds: 10
        env:
        - name: SERVICE
          value: mysql
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ft-secret
              key: mysql_pass
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: ft-secret
              key: db_name
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: ft-secret
              key: db_name
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ft-secret
              key: db_pass
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: mysql
