# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    wordpress.yml                                      :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kefujiwa <kefujiwa@student.42tokyo.jp>     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/05/23 22:38:35 by kefujiwa          #+#    #+#              #
#    Updated: 2021/05/30 16:57:10 by kefujiwa         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      name: wordpress
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: kefujiwa/wordpress:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
        livenessProbe:
          exec:
            command: ["/bin/sh", "-c", "pgrep telegraf && pgrep nginx && pgrep php-fpm"]
          initialDelaySeconds: 10
          periodSeconds: 5
        env:
        - name: SERVICE
          value: wordpress-service
        - name: DATABASE
          value: wordpress
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: ft-secret
              key: db_name
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: ft-secret
              key: db_user
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ft-secret
              key: db_pass
        - name: WORDPRESS_DB_HOST
          value: mysql-service:3306
        volumeMounts:
        - name: wordpress-storage
          mountPath: /var/www/wordpress
      volumes:
      - name: wordpress-storage
        persistentVolumeClaim:
          claimName: wordpress-pvc
        
---

apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  labels:
    app: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: ft_services
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
  - port: 5050
    targetPort: 5050
    protocol: TCP
    name: wordpress
